### PR TITLE
provider-config: Append port to hostname instead of the URL

### LINKED ISSUE #539: Fails if remote address contains a subdirectory
# summary
The following settings will fail.
```tf
 remote {
    name    = "ubuntu-ex"
    protocol = "simplestreams"
    address = "https://example.com/ubuntu-cloud-images/releases/"
  }
```
※Domain section is hidden.

```
resource "lxd_cached_image" "image" {
    source_remote   = "ubuntu-ex"
    source_image    = "24.04"
    type            = "container"
}
```

Errors are as follows
```
│ Failed getting image: Failed parsing stream: Unable to fetch
│ https://example.com/ubuntu-cloud-images/releases/:443/streams/v1/index.json: 404 Not Found
```

https://example.com/ubuntu-cloud-images/releases/streams/v1/index.json
has been confirmed to exist.

# What you need to fix
I want the port number to come to the proper location when making http requests.

https://example.com/ubuntu-cloud-images/releases/:443/streams/v1/index.json
↓
https://example.com:443/ubuntu-cloud-images/releases/streams/v1/index.json

### PR DESCRIPTION
**Pull request by MusicDin**
Closes #539

### CODE REVIEW

File: internal/provider-config/config.go [hunk 1]
```diff
@@ -569,10 +569,10 @@ func DetermineLXDAddress(protocol string, address string) (string, error) {
 				port = "443"
 			}
 
-			address = fmt.Sprintf("%s:%s", address, port)
+			url.Host = fmt.Sprintf("%s:%s", url.Hostname(), port)
```
Comment (simondeziel) [inline internal/provider-config/config.go:572]: Since we are dealing with strings I'd avoid the call to `Sprintf`:
```suggestion
			url.Host = url.Hostname() + ":" + port
```
But it's not performance critical ;)

**Review by simondeziel — APPROVED** [review]
